### ISSUE TITLE
Can you explain why you initialize weights to 0 ? 

### ISSUE THREAD

**Issue by Cyril9227** [gbup-group/IEBN#1]
Hello, 

In the iebn_resnet.py file, I'm wondering why do you initialize weight_readjust to 0 and bias_readjust to -1, usually bias are initialized at 0 and weights with a certain distribution... 

self.weight_readjust.data.fill_(0)
self.bias_readjust.data.fill_(-1)

Thank's in advance,

**Comment by zzk2021** [comment]
I also confused , I want to reference this work but I dont understand why he did that

**Comment by zzk2021** [comment]
and why he didn't release the style transfer work in his paper？
